
name: .NET Core

on:

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

  pull_request:
    branches: [ master ]
    paths-ignore: 
      - 'docs/**'
      - '**.md'

jobs:
  buildJob:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        runtime: ["win-x86", "win-arm", "win-arm64", "win7-x64", "win7-x86", "win81-x64", "win81-x86", "win81-arm", "win10-x64", "win10-x86", "win10-arm", "win10-arm64", "linux-x64", "linux-musl-x64", "linux-arm", "linux-arm64", "rhel-x64", "rhel.6-x64", "osx-x64", "osx.10.10-x64", "osx.10.11-x64", "osx.10.12-x64", "osx.10.13-x64", "osx.10.14-x64"]

    steps:
    - uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow   
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.2
      with:
          versionSpec: '5.2.x'        
        
    - name: GitVersion
      uses: docker://gittools/gitversion:5.2.5-linux-ubuntu-16.04-netcoreapp2.1
      with:
        args: /github/workspace /nofetch /output buildserver

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:AssemblyVersion=${{ env.GitVersion_AssemblySemVer }} /p:FileVersion=${{ env.GitVersion_AssemblySemFileVer }} /p:InformationalVersion=${{ env.GitVersion_InformationalVersion }}
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Publish ${{ matrix.runtime }}
      run: dotnet publish .//SmartThingsTerminal//SmartThingsTerminal.csproj -o publish/v${{ env.GitVersion_SemVer }}/${{ matrix.runtime }} -c Release -r ${{ matrix.runtime }} -f netcoreapp3.1 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:AssemblyVersion=${{ env.GitVersion_AssemblySemVer }} /p:FileVersion=${{ env.GitVersion_AssemblySemFileVer }} /p:InformationalVersion=${{ env.GitVersion_InformationalVersion }}

    - name: Zip ${{ matrix.runtime }} release
      uses: papeloto/action-zip@v1
      with:
        files: publish/v${{ env.GitVersion_SemVer }}/${{ matrix.runtime }}/
        recursive: true
        dest: v${{ env.GitVersion_SemVer }}-${{ matrix.runtime }}.zip

    - name: Upload all pre-release artifacts
      uses: actions/upload-artifact@v2
      with:
        name: v${{ env.GitVersion_SemVer }}/${{ matrix.runtime }}
        path: publish/v${{ env.GitVersion_SemVer }}/${{ matrix.runtime }}/

